# Sample .travis.yml for R projects.
#
# See the r-travis repo and its wiki
#   https://github.com/craigcitro/r-travis/wiki
#   https://github.com/eddelbuettel/r-travis/
sudo: false

language: r
cache: packages

os:
  - linux
  - osx

r:
  - release
  - devel

r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
